// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function MarkdownerFile(arg1) {
  return window['go']['main']['App']['MarkdownerFile'](arg1);
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}
