// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlatform():Promise<string>;

export function MarkdownerFile(arg1:string):Promise<string>;

export function ReadDir(arg1:string):Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<string>;
